### ISSUE TITLE
Unable to get/set username for users

### ISSUE THREAD

**Issue by HadynM-TWoA** [jamesbar2/SchooxSharp#1]
Hi

I understand this is being looked at now.  Are you able to provide an ETA?

Cheers Hadyn

**Comment by jamesbar2** [comment]
Hadyn,

I just pushed out an update to the client, it should address "username" not being properly set.  Give the new version a try and see if its now working for you.

Thanks!
-James

**Comment by HadynM-TWoA** [comment]
Still no joy.  Retrieving a users details provides the following (changed id and name):
Id: 1234567, UserId: , FirstName: Kris, LastName: Berny, Password: , Email: kris.berny@twoa.ac.nz, Image: //static-cdn.schoox.com/user/images/no-user-image_small.gif, Url: https://www.schoox.com/user/1234567/, TotalCourseHours: , TotalCourses: , TotalExams: , DueDate: , Progress: , Time: , EnrollmentDate: , Attempts: , ProfileUrl: , Active: True, Roles: System.Collections.Generic.List`1[System.String], Units: System.Collections.Generic.List`1[SchooxSharp.Api.Models.Unit], Certificates: System.Collections.Generic.List`1[SchooxSharp.Api.Models.Certificate]

UserId is still blank even though it is populated in Schoox.

**Comment by HadynM-TWoA** [comment]
Just checked and the username isn't in the NewUser model either.  Does that mean at least two api calls add a user and set their username?

**Comment by jamesbar2** [comment]
Hadyn,

Check now.  I've tested getting a user, and when present the Username field is populating.  I've also deprecated UserId since it was confusing between the API and SchooxSharp.  UserId will continue to operate, it just points to the Username property now.

Please check the Username when creating a new user.  Hopefully this should resolve the issue!

-James

**Comment by HadynM-TWoA** [comment]
Thank James

I have tested retrieving a user and adding a user with the usernames and both were successful. 

Cheers Hadyn

**Comment by jamesbar2** [comment]
Excellent. Let me know if you have any other issues. Thanks for helping us out.
