### ISSUE TITLE
UsersTests broken

### ISSUE THREAD

**Issue by Will-Compeat** [jamesbar2/SchooxSharp#2]
NewUser constructors were augmented with a required 'string username' parameter, but the UsersTests were not updated to reflect the new signature.

**Comment by jamesbar2** [comment]
So this is now a required parameter to create a user?  Sorry for the delay, I was out of the country.

**Comment by bhudgeons** [comment]
username is not required by the API

**Comment by jamesbar2** [comment]
If that's the case, @bhudgeons do the tests need to be updated for a non-required parameter?  Also, the NewUser test is not a test that is executed; since I don't have access to a sandbox test server.  The only tests that are actually enabled are GET tests.
